# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b478f65b5a1865c09be3351217ae56c92188ec5078b357a1334278589874d4260a00bc08697210c0ad677e5c3c243be911bbdffb3b21e34446212527239a14f2

test:
  secret_key_base: 4f47379ef5a1f9f51c2fa1dbd22b1c6df62c6c938e5abbb5c471a8be88119efd1707a9c7e06e1d20968e939fcc6dda359704126f11e3d1376ccd3dac07f004ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
